org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

#Mod
archives_base_name=copycats
maven_group=com.copycatsplus
mod_authors=Lysine, Bennyboy1695, Redcat_XVIII
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=All the copycats you've ever wanted, combined into a single mod!
mod_name=Create: Copycats+
mod_license=All Rights Reserved

#Minecraft and Mappings
minecraft_version=1.20.1
parchment_version=2023.09.03

#Mod Loaders
enabled_platforms=fabric,forge
fabric_loader_version=0.15.9
fabric_api_version=0.92.0+1.20.1
forge_version=1.20.1-47.2.20

#Common Properties
#One boolean for both fabric and forge
doDryRun=false
mixin_extras_version=0.3.2
jei_common_version=15.3.0.4
embeddium_curse_id=5522040

#Forge Properties
create_forge_version=0.5.1.j-55
create_forge_range=[0.5.1.d,)
registrate_forge_version=MC1.20-1.3.3
flywheel_forge_minecraft_version=1.20.1
flywheel_forge_version=0.6.11-13
# JEI 10+ seems to have issues on Forge, so the versions must be different for now. # 1.19 edit: no version < 11 exists, so use that
jei_forge_version=15.3.0.4
embeddium_forge_curse_id=5681725
additionalplacements_forge_curse_id=6057797
double_slabs_forge_curse_id=3873442
jade_forge_curse_id=5390389
athena_forge_curse_id=5176879
tfmg_forge_curse_id=5505872
extended_cogwheels_forge_curse_id=5229925
spark_forge_curse_id=4738952
moonlight_curse_forge_id=5975794
vertical_slabs_curse_forge_id=5691543

#Fabric Properties
create_fabric_version=0.5.1-f-build.1417+mc1.20.1
create_fabric_range=>=0.5.1-d-build.1161
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files
jei_fabric_version=15.3.0.4
config_port_version=8.0.0
continuity_curse_version=5344958
jade_fabric_curse_id=5339230
athena_fabric_curse_id=5176880
indium_fabric_curse_id=5493195
sodium_fabric_version=mc1.20.1-0.5.11
extended_cogwheels_fabric_version=2.1.1-1.20.1-0.5.1.f-fabric
spark_fabric_curse_id=4738953
moonlight_curse_fabric_id=5975796
vertical_slabs_curse_fabric_id=5691542
additionalplacements_fabric_curse_id=6057817