org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

#Mod
archives_base_name=copycats
maven_group=com.copycatsplus
mod_authors=Lysine, Bennyboy1695, Redcat_XVIII
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=All the copycats you've ever wanted, combined into a single mod!
mod_name=Create: Copycats+
mod_license=All Rights Reserved

#Minecraft and Mappings
minecraft_version=1.19.2
parchment_version=2022.11.27

#Mod Loaders
enabled_platforms=fabric,forge
fabric_loader_version=0.16.10
fabric_api_version=0.77.0+1.19.2
forge_version=1.19.2-43.2.4

#Common Properties
#One boolean for both fabric and forge
doDryRun=false
mixin_extras_version=0.3.2
jei_common_version=11.6.0.1019
embeddium_curse_id=5539178

#Forge Properties
create_forge_version=0.5.1.f-46
create_forge_range=[0.5.1.f,)
registrate_forge_version=MC1.19-1.1.5
flywheel_forge_minecraft_version=1.19.2
flywheel_forge_version=0.6.10-20
# JEI 10+ seems to have issues on Forge, so the versions must be different for now. # 1.19 edit: no version < 11 exists, so use that
jei_forge_version=11.6.0.1019
embeddium_forge_curse_id=5539178
additionalplacements_forge_curse_id=6057790
double_slabs_forge_curse_id=3873442
jade_forge_curse_id=4914105
tfmg_forge_curse_id=5505873
extended_cogwheels_forge_curse_id=5229924
spark_forge_curse_id=4505309
moonlight_curse_forge_id=5567102
vertical_slabs_curse_forge_id=4808086

#Fabric Properties
create_fabric_version=0.5.1-f-build.1347+mc1.19.2
create_fabric_range=>=0.5.1-d-build.1193
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files
jei_fabric_version=11.6.0.1019
config_port_version=4.2.9
continuity_curse_version=4441032
jade_fabric_curse_id=4328558
indium_fabric_curse_id=3957480
sodium_fabric_version=mc1.19.2-0.4.4
extended_cogwheels_fabric_version=2.1.1-1.19.2-0.5.1.f-fabric
spark_fabric_curse_id=4505310
moonlight_curse_fabric_id=5567103
vertical_slabs_curse_fabric_id=4322500
additionalplacements_fabric_curse_id=6057815
