org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

#Mod
archives_base_name=copycats
maven_group=com.copycatsplus
mod_authors=Lysine, Bennyboy1695, Redcat_XVIII
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=All the copycats you've ever wanted, combined into a single mod!
mod_name=Create: Copycats+
mod_license=All Rights Reserved
mod_credits=The Create: Addon Hub Discord
mod_issues=https://github.com/copycats-plus/copycats/issues
mod_url=https://github.com/copycats-plus/copycats

#Minecraft and Mappings
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
parchment_version=2024.11.17

#Mod Loaders
enabled_platforms=fabric,neoforge

fabric_loader_version=0.16.10
fabric_api_version=0.115.4+1.21.1

neoforge_version=21.1.213
neoforge_version_range=[21.1.200,)
neoforge_loader_version_range=[1,)

#Common Properties
#One boolean for both fabric and forge
doDryRun=false
mixin_extras_version=0.4.1
jei_common_version=19.21.0.247
emi_common_version=1.1.22
sodium_curse_id=6382651
diagonal_mods_version=8.0.5
ponder_version=1.0.66

#NeoForge Properties
create_neoforge_version=6.0.8-168
create_neoforge_range=[6.0.8,)
registrate_neoforge_version=MC1.21-1.3.0+62
flywheel_neoforge_minecraft_version=1.21.1
flywheel_neoforge_version=1.0.5
# JEI 10+ seems to have issues on Forge, so the versions must be different for now. # 1.19 edit: no version < 11 exists, so use that
jei_neoforge_version=19.21.0.247
sodium_neoforge_curse_id=6382651
additionalplacements_neoforge_curse_id=6596674
double_slabs_neoforge_curse_id=3873442
jade_neoforge_curse_id=5390389
athena_neoforge_curse_id=5629395
tfmg_neoforge_curse_id=5505872
extended_cogwheels_neoforge_curse_id=5229925
spark_neoforge_curse_id=4738952
moonlight_curse_neoforge_id=5975794
vertical_slabs_curse_neoforge_id=5691543

#Fabric Properties
create_fabric_version=6.0.0.0+mc1.20.1-build.1653
create_fabric_range=>=6.0.0
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files
jei_fabric_version=19.21.0.247
config_port_version=8.0.0
continuity_curse_version=5962874
jade_fabric_curse_id=5339230
athena_fabric_curse_id=5629396
indium_fabric_curse_id=5493195
sodium_fabric_version=mc1.20.1-0.5.11
extended_cogwheels_fabric_version=2.1.1-1.20.1-0.5.1.f-fabric
spark_fabric_curse_id=4738953
moonlight_curse_fabric_id=5975796
vertical_slabs_curse_fabric_id=5691542
additionalplacements_fabric_curse_id=6057817