architectury {
    common(enabled_platforms.split(","))
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    // Compile against Create Fabric in common
    // beware of differences across platforms!
    // dependencies must also be pulled in to minimize problems, from remapping issues to compile errors.
    // All dependencies except Flywheel and Registrate are NOT safe to use!
    // Flywheel and Registrate must also be used carefully due to differences.
    modCompileOnly("com.simibubi.create:create-fabric-${minecraft_version}:${create_fabric_version}")
    // required for proper remapping and compiling
    modCompileOnly("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_common_version}")

    modCompileOnly("curse.maven:additional-placements-fabric-930469:${additionalplacements_fabric_curse_id}")
    modCompileOnly("curse.maven:embeddium-908741:${embeddium_curse_id}")
    modCompileOnly("curse.maven:selene-499980:${moonlight_curse_fabric_id}")
    modCompileOnly("curse.maven:vertical-slabs-compat-724387:${vertical_slabs_curse_fabric_id}")

    //Used for all diagonal mods as they all shadow a common library we can mixin
    modCompileOnly("fuzs.diagonalblocks:diagonalblocks-common:${diagonal_mods_version}")

    annotationProcessor(implementation("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
}
